### ISSUE TITLE
GenDist is NaN after running single_snp analysis

### ISSUE THREAD

**Issue by lucasmiranda42** [fastlmm/FaST-LMM#11]
Hi!
First of all, thank you for such a great tool!
After using it a few times and getting the expected results, I now stumbled upon a dataset from which I get NaN values for all genetic distances. I'm running the code below, independently, for each chromosome of an imputed dataset. As K0 I'm passing the full unimputed genome for the same set of samples. The code is part of a SnakeMake pipeline; input.imp_bed and input.dst_bed are strings with the names of the mentioned testing and distance bed files, respectively. I checked all inputs for missing data, malformations, etc. and nothing I came up with seemed to be the case. I don't think it's a bug, but rather a mistake on my side. Is there any obvious hint?
Thanks a lot!

`snpdata = Bed(input.imp_bed)[:,::2].read()`
`snpdist = Bed(input.dst_bed)[:,::2].read()`
`results_df = single_snp(test_snps=snpdata, pheno=input.phenos, K0=snpdist, count_A1=False,`
`                      leave_out_one_chrom=True)`
`results_df.to_csv(output.gwas, sep="\t")`

**Comment by CarlKCarlK** [comment]
Lucas,

Thanks for using FaST-LMM and PySnpTools. (I see and appreciate that you’re using the slicing features of PySnpTools, e.g. “[:,::2]”)

Summary:

It may just mean that your Bed file has some genetic distances set to unknown.

Details:

We recently changed the Bed reader to be consistent with the other SnpReaders (https://fastlmm.github.io/PySnpTools/#snpreader-snpreader). I suspect that change may be giving you unexpected results. Specifically, in a BED file if a genetic distance is unknown, it should be set  to “0”. However, other SnpReaders don’t follow that standard, so now the Bed reader changes any “0”’s to NaN.

Please check your Bed file for missing genetic distance values. Some example code is below. (If your *.bim file is not too big, you can also open it in a text editor and look for “0”’s in the 3rd column.)

import numpy as np
from pysnptools.snpreader import Bed
from pysnptools.util import example_file # Download and return local file name

bedfile = example_file("tests/datasets/all_chr.maf0.001.N300.*","*.bed")

bed = Bed(bedfile)
nans = np.isnan(bed.pos)

for i,what in enumerate(["chromosome","genetic distance", "basepair distance"]):
    print(f"{nans[:,i].sum()} missing values of {nans.shape[0]} in {what}")
output:
0 missing values of 1015 in chromosome
2 missing values of 1015 in genetic distance
17 missing values of 1015 in basepair distance

Please, let me know if this takes care of the problem.

Yours,
Carl


Carl Kadie, Ph.D.
FaST-LMM & PySnpTools Team<https://fastlmm.github.io/>
(Microsoft Research, retired)
https://www.linkedin.com/in/carlk/

Join the FaST-LMM user discussion and announcement list via email<mailto:fastlmm-user-join@python.org?subject=Subscribe> (or use web sign up<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fmail.python.org%2Fmailman3%2Flists%2Ffastlmm-user.python.org&data=02%7C01%7C%7C13a5c33d7cd84cad5cdf08d7bba56e20%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637184191498409587&sdata=2CQWjQEwOpQol2rQ1eoyVTgY8WvInV8UH31Wtl68FzY%3D&reserved=0>)

**Comment by lucasmiranda42** [comment]
Dear Carl,
Thank you very much for your quick answer! I'll try out your suggestions this afternoon and let you know.
Best and have a nice day,
Lucas

**Comment by lucasmiranda42** [comment]
Dear Carl,

I checked and all .bim files in the dataset indeed had a dummy value of '0' in the 3rd column. Adding genetic distance annotations with plink fixed the issue.

Thank you very much for your help!
Lucas

**Comment by CarlKCarlK** [comment]
Lucas,

Sadly, the single_snp function just reports the values it finds in the *.bim file.

I wonder if you could look up the genetic distance from the SNP name. For example, if you know you have (human) rs6313, there seem to be on-line references (e.g. rs6313 - Wikipedia<https://en.wikipedia.org/wiki/Rs6313>, rs6313 - SNPedia<https://www.snpedia.com/index.php/Rs6313>) that give at least the position and I imagine genetic distance.


  *   Carl

p.s. Also see these threads.
Conversion of physical position (bp) of SNPs to genetic postion (cM) (researchgate.net)<https://www.researchgate.net/post/Conversion-of-physical-position-bp-of-SNPs-to-genetic-postion-cM>
