### ISSUE TITLE
Result of single_snp analysis has fewer SNPs than input

### ISSUE THREAD

**Issue by lucasmiranda42** [fastlmm/FaST-LMM#14]
Hi! Me again :)

I ran a standard GWAS analysis using single_snp, and I realized after screening the results that I have way fewer rows in the resulting DataFrame than in the original input (suspiciously close to half, actually).

My code (part of a snakemake rule):

```
input:
        imp_bed="../08-data_ready_for_GWAS/ped_GWAS_imputed_chr{chrom}_{pheno}.QC_onlysnps.bed",
        dst_bed="../08-data_ready_for_GWAS/ped_GWAS_imputed_{pheno}_gendist_LOO.bed",
        phenos="../../data/withprocam/{pheno}_procam.phen",
    output:
        gwas="../09-GWAS_results/LMM_{pheno}_gwas_output_chr{chrom}",
    run:
        snpdata = Bed(input.imp_bed)[:, ::2].read()
        snpdist = Bed(input.dst_bed)[:, ::2].read()
        results_df = single_snp(
            test_snps=snpdata,
            pheno=input.phenos,
            K0=snpdist,
            count_A1=True,
            leave_out_one_chrom=True,
        )
        results_df.to_csv(output.gwas, sep="\t")
```

input.imp_bed has 557226 for chromosome 1, and the output yields only 278614 summary statistics.
Also, for K0 I'm using an unimputed version of the data, with way fewer SNPs (263429 for all chromosomes).

Is there anything obvious that I'm doing wrong?

Thanks!
Lucas

**Comment by CarlKCarlK** [comment]
Lucas,

Thanks for using FaST-LMM!

I think I see the problem. In

        snpdata = Bed(input.imp_bed)[:, ::2].read()

        snpdist = Bed(input.dst_bed)[:, ::2].read()
you're using every 2nd SNP.

You may have meant to work with every 2nd individual, which would look like this:

        snpdata = Bed(input.imp_bed)[::2, :].read()

        snpdist = Bed(input.dst_bed)[::2, :].read()


As far as I can tell everything else looks fine (and it's nice to see someone using the fancy indexing features PySnptools!)


[I'll be away most of today. Thanks for the Manhattan plot suggestion. I'll look at it soon.]


  *   Carl


Carl Kadie, Ph.D.
FaST-LMM & PySnpTools Team<https://fastlmm.github.io/>
(Microsoft Research, retired)
https://www.linkedin.com/in/carlk/

Join the FaST-LMM user discussion and announcement list via ***@***.***?subject=Subscribe> (or use web sign up<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fmail.python.org%2Fmailman3%2Flists%2Ffastlmm-user.python.org&data=02%7C01%7C%7C13a5c33d7cd84cad5cdf08d7bba56e20%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637184191498409587&sdata=2CQWjQEwOpQol2rQ1eoyVTgY8WvInV8UH31Wtl68FzY%3D&reserved=0>)

From: Lucas Miranda ***@***.***>
Sent: Tuesday, March 23, 2021 5:33 AM
To: fastlmm/FaST-LMM ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [fastlmm/FaST-LMM] Result of single_snp analysis has fewer SNPs than input (#14)


Hi! Me again :)

I ran a standard GWAS analysis using single_snp, and I realized after screening the results that I have way fewer rows in the resulting DataFrame than in the original input (suspiciously close to half, actually).

My code (part of a snakemake rule):

input:

        imp_bed="../08-data_ready_for_GWAS/ped_GWAS_imputed_chr{chrom}_{pheno}.QC_onlysnps.bed",

        dst_bed="../08-data_ready_for_GWAS/ped_GWAS_imputed_{pheno}_gendist_LOO.bed",

        phenos="../../data/withprocam/{pheno}_procam.phen",

    output:

        gwas="../09-GWAS_results/LMM_{pheno}_gwas_output_chr{chrom}",

    run:

        snpdata = Bed(input.imp_bed)[:, ::2].read()

        snpdist = Bed(input.dst_bed)[:, ::2].read()

        results_df = single_snp(

            test_snps=snpdata,

            pheno=input.phenos,

            K0=snpdist,

            count_A1=True,

            leave_out_one_chrom=True,

        )

        results_df.to_csv(output.gwas, sep="\t")

input.imp_bed has 557226 for chromosome 1, and the output yields only 278614 summary statistics.
Also, for K0 I'm using an unimputed version of the data, with way fewer SNPs (263429 for all chromosomes).

Is there anything obvious that I'm doing wrong?

Thanks!
Lucas

-

**Comment by lucasmiranda42** [comment]
Oh, silly me... thanks a lot!
I'll try it out and confirm that it works :)

**Comment by lucasmiranda42** [comment]
Worked like a charm. Thanks!
