### ISSUE TITLE
Installing fast-lmm on CentOS 7 

### ISSUE THREAD

**Issue by snowformatics** [fastlmm/FaST-LMM#18]
Hi Carl,

we are trying to setup a flask App with fast-lmm on CentOS 7  but the installation fails. 

Here is the error message:
https://github.com/snowformatics/gwas_web_production/issues/1

Do you have any idea what's going wrong?

Thanks a lot in advance
Stefanie

**Comment by CarlKCarlK** [comment]
Stefanie,

Thanks again for using FaST-LMM!

A while back, pip changed, and we had to change the install instructions for FaST-LMM. Please check that you install like this:

If you have Miniconda or Anaconda installed, installation is as easy as:
conda install "mkl==2019.4" "scipy" "numpy"
pip install --no-build-isolation fastlmm

Let me knows what happens. If that doesn't work, I'll try to repro on a CentOS 7 virtual machine.


  *   Carl

From: snowformatics ***@***.***>
Sent: Thursday, June 17, 2021 4:56 AM
To: fastlmm/FaST-LMM ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [fastlmm/FaST-LMM] Installing fast-lmm on CentOS 7 (#18)
Importance: High


Hi Carl,

we are trying to setup a flask App with fast-lmm on CentOS 7 but the installation fails.

Here is the error message:
snowformatics/gwas_web_production#1<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fsnowformatics%2Fgwas_web_production%2Fissues%2F1&data=04%7C01%7C%7C6631761a1b4a4ea17ee408d93186eb54%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637595277799845008%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=e78uI5fMaVGPQSjvzsX4pWYHdaVuUlQONIsZW9G2pYw%3D&reserved=0>

Do you have any idea what's going wrong?

Thanks a lot in advance
Stefanie

-

**Comment by Xenokrates** [comment]
Hi,

**yes it works** like Carl described with a _miniconda_ environment running as normal user under CentOS. I will describe my test setting in the issue mentioned above.

Best regards
H.

**Comment by snowformatics** [comment]
Great news, thanks to both of you!
