### ISSUE TITLE
Some tests are skipped due to duplicate names

### ISSUE THREAD

**Issue by code-review-doctor** [fastlmm/FaST-LMM#22]
Test names must be unique per scope otherwise the second test overrides the first one with the same name.

For example if you had a test file that does:

```
def test_a():
    pass

def test_a():
    pass
```

Then only the second `test_a` will be ran. More details [here](https://codereview.doctor/features/python/best-practice/avoid-duplicate-unit-test-names).

These are the tests that are overriding previously defined tests due to this problem:

https://github.com/fastlmm/FaST-LMM/blob/d1fdad820ebb80329b39cedf8e599ef33230487e/fastlmm/association/tests/test_snp_set.py#L145

I found this issue automatically, see other issues [here](https://codereview.doctor/fastlmm/FaST-LMM)

**Comment by CarlKCarlK** [comment]
Thanks. Will fix.
