### ISSUE TITLE
How to tell which allele is used as reference for effect size estimates?

### ISSUE THREAD

**Issue by CSGallagher** [fastlmm/FaST-LMM#24]
Hi. Apologies if it's answered elsewhere, but I'm having a hard time finding documentation that clearly states which allele FastLMM uses as the reference for beta/SNPWeight estimates? Is it the minor allele, the allele in the fifth column of the bim file (Allele 1), or the allele in the sixth column of the bim file (Allele 2)? 

For reference: https://www.cog-genomics.org/plink/1.9/formats#bim

**Comment by CarlKCarlK** [comment]
Scott,

Thanks for your question and thanks for using FaST-LMM.

By default, FaST-LMM turns Bed data into 0,1,2 values by counting the number of allele2 (the 6th column). This is for historical reasons and is the opposite of the PLINK standard which counts the number of allele 1's (the 5th column). You can change the default by setting single_snp's "count_A1" option to True. https://fastlmm.github.io/FaST-LMM/#single-snp. Alternatively, you can use the PySnpTools Bed reader explicitly, again setting "count_A1" to True. https://fastlmm.github.io/PySnpTools/#snpreader-bed

Yours,


  *   Carl


From: c scott gallagher ***@***.***>
Sent: Wednesday, March 02, 2022 3:40 PM
To: fastlmm/FaST-LMM ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [fastlmm/FaST-LMM] How to tell which allele is used as reference for effect size estimates? (Issue #24)
Importance: High


Hi. Apologies if it's answered elsewhere, but I'm having a hard time finding documentation that clearly states which allele FastLMM uses as the reference for beta/SNPWeight estimates? Is it the minor allele, the allele in the fifth column of the bim file (Allele 1), or the allele in the sixth column of the bim file (Allele 2)?

For reference: https://www.cog-genomics.org/plink/1.9/formats#bim<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.cog-genomics.org%2Fplink%2F1.9%2Fformats%23bim&data=04%7C01%7C%7Ce78a776618d74be3befd08d9fca6095b%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637818612314699592%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=lo5aT1k8WRJPYbgqH1fP4evMkRpo8uGMltouXg82b0Q%3D&reserved=0>

-
Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Ffastlmm%2FFaST-LMM%2Fissues%2F24&data=04%7C01%7C%7Ce78a776618d74be3befd08d9fca6095b%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637818612314699592%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=VOOSifQ5qTpcUDIqfeWxjquCr2KeemOdGgLjkbftTkk%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FABR65P5KC3ILGHCGRQ4YEALU57363ANCNFSM5PY44TVA&data=04%7C01%7C%7Ce78a776618d74be3befd08d9fca6095b%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637818612314699592%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=G7j9vod8mM5Nxhp1Re3FGa%2FOpQ35ZfSWhQEZtG%2Bu504%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7Ce78a776618d74be3befd08d9fca6095b%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637818612314699592%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=1u1wbiaW1myB1TKzYUVLx%2FVznfTCfKbqPoKH3gGLRMA%3D&reserved=0> or Android<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7Ce78a776618d74be3befd08d9fca6095b%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637818612314699592%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=jHRrnEl0cej4kn3qFF5Pbn6MiitqjP%2BHXZM2OL7%2FNxM%3D&reserved=0>.

**Comment by CSGallagher** [comment]
Thank you so much for the speedy responses on both topics, Carl. FastLMM has been an incredible tool, and I really appreciate the thorough documentation. If I have any more questions, I'll reach out.
