### ISSUE TITLE
Scaling of beta estimates with case control analyses

### ISSUE THREAD

**Issue by CSGallagher** [fastlmm/FaST-LMM#25]
Hello.  I am using the single.snp functionality from FastLMM and am clearly able to replicate strengths of associations with respect to p-values. However, when I run single.snp with a binary case-control outcome, I've noticed that I see much smaller effect size estimates than other tools. In Bolt-LMM, there are case-fraction-based adjustments that must be made to the beta values from logistic regression analyses prior to transforming to an Odd's Ratio. Is there a similar scaling step that must be done for the beta/SnpWeight obtained from running FastLMM on a binary outcome prior to converting to an odds ratio?
<img width="982" alt="Screen Shot 2022-03-02 at 3 45 52 PM" src="https://user-images.githubusercontent.com/60437500/156468689-524f3758-b420-4fba-a4c2-a849442ebd29.png">

**Comment by CarlKCarlK** [comment]
Scott,

Thanks for your queries and thanks for using FaST-LMM!

We're conferring and should have some information in the next couple of days.

Yours,
Carl


Carl Kadie, Ph.D.
FaST-LMM & PySnpTools Team<https://fastlmm.github.io/>
(Microsoft Research, retired)
https://www.linkedin.com/in/carlk/

Join the FaST-LMM user discussion and announcement list via ***@***.***?subject=Subscribe> (or use web sign up<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fmail.python.org%2Fmailman3%2Flists%2Ffastlmm-user.python.org&data=02%7C01%7C%7C13a5c33d7cd84cad5cdf08d7bba56e20%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637184191498409587&sdata=2CQWjQEwOpQol2rQ1eoyVTgY8WvInV8UH31Wtl68FzY%3D&reserved=0>)

**Comment by CarlKCarlK** [comment]
Scott,

Another good question! It took us a while, but we found the answer in the documentation (sorry, that it is somewhat hidden):

[From https://nbviewer.org/github/fastlmm/FaST-LMM/blob/master/doc/ipynb/FaST-LMM.ipynb]

Data preparation
This version of FaST-LMM is designed for use with randomly ascertained data with Gaussian residuals. If you have case-control data with substantial ascertainment bias, you should first transform your phenotype(s) using LEAP<https://github.com/omerwe/LEAP> (Weissbrod et al., arXiv 2014). If you are analyzing continuous phenotypes with non-Gaussian residuals, you should first transform your phenotype(s) using Warped-LMM<https://github.com/PMBio/warpedLMM> (Fusi et al., Nature Commun 2014).

We hope this helps. Thanks again for using FaST-LMM.

Yours,
Carl


From: c scott gallagher ***@***.***>
Sent: Wednesday, March 02, 2022 3:46 PM
To: fastlmm/FaST-LMM ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [fastlmm/FaST-LMM] Scaling of beta estimates with case control analyses (Issue #25)
Importance: High


Hello. I am using the single.snp functionality from FastLMM and am clearly able to replicate strengths of associations with respect to p-values. However, when I run single.snp with a binary case-control outcome, I've noticed that I see much smaller effect size estimates than other tools. In Bolt-LMM, there are case-fraction-based adjustments that must be made to the beta values from logistic regression analyses prior to transforming to an Odd's Ratio. Is there a similar scaling step that must be done for the beta/SnpWeight obtained from running FastLMM on a binary outcome prior to converting to an odds ratio?
[Screen Shot 2022-03-02 at 3 45 52 PM]<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F60437500%2F156468689-524f3758-b420-4fba-a4c2-a849442ebd29.png&data=04%7C01%7C%7C75f40f341f9140a7e80708d9fca6d606%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637818615760042241%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=0UW4VQAGrD4kgwh9907oYmTDWc2%2FAQ7HnxiWh7FR%2FLg%3D&reserved=0>

-
Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Ffastlmm%2FFaST-LMM%2Fissues%2F25&data=04%7C01%7C%7C75f40f341f9140a7e80708d9fca6d606%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637818615760198471%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=vAOpQ0u5xuHMWBCe4FSioYU9%2BczBir34hnQUPGGA0G0%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FABR65P56WBPHWZTK22QPOS3U574UJANCNFSM5PY5GKEQ&data=04%7C01%7C%7C75f40f341f9140a7e80708d9fca6d606%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637818615760198471%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=mLhUi3NQmm776y4rtmmYuzD4x0L4W32lli5KpY5tZzM%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7C75f40f341f9140a7e80708d9fca6d606%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637818615760198471%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=fVTSdsFX8bBgDUhp1BWUO01h1IoQVL1X6GwSBmp2QgE%3D&reserved=0> or Android<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7C75f40f341f9140a7e80708d9fca6d606%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637818615760198471%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Hub0sGnKQWwPGIQtAFujOX9X4YBvrBUVyfQKYYYr0XI%3D&reserved=0>.
