### ISSUE TITLE
Hapmap format 

### ISSUE THREAD

**Issue by snowformatics** [fastlmm/FaST-LMM#28]
Hi everyone,

Does anyone has experience with genotypic data stored in Hapmap format? What would be the best approach to convert the data? Would it work to convert it to hdf5 or must I go for Hapmap > vcf > bed?

Thanks for any tips

**Comment by CarlKCarlK** [comment]
Hi,

I think FaST-LMM's flavor of HDF5 is different than anyone else's, so Hapmap, to VCF, to PLINK Bed is likely necessary.

I did see this for converting from hapmap to PLINK Bed format:
   http://poissonfish.github.io/iPat/convert-hapmap-to-plink-format.html

And as you likely already know the plink tool is good for VCF to PLINK Bed
    https://www.researchgate.net/post/Coverting-vcf-files-to-plink-bed-format


  *   Carl

From: snowformatics ***@***.***>
Sent: Monday, March 14, 2022 12:17 AM
To: fastlmm/FaST-LMM ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [fastlmm/FaST-LMM] Hapmap format (Issue #28)
Importance: High


Hi everyone,

Does anyone has experience with genotypic data stored in Hapmap format? What would be the best approach to convert the data? Would it work to convert it to hdf5 or must I go for Hapmap > vcf > bed?

Thanks for any tips

-
Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Ffastlmm%2FFaST-LMM%2Fissues%2F28&data=04%7C01%7C%7C3fe5ad8738384ffe782c08da058aac53%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637828390402636246%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=yFnWH4GuxuLtFgO%2FlzbyDWG3V4R5QcHScJTDMQadU4w%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FABR65P3HYT557WI5K3TTLSTU73RX3ANCNFSM5QUUMBUQ&data=04%7C01%7C%7C3fe5ad8738384ffe782c08da058aac53%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637828390402636246%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=HuriX9pnSqs70mxI1%2B5pWbx%2Fhc3%2BrCHeaOWn22ty2GE%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7C3fe5ad8738384ffe782c08da058aac53%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637828390402636246%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=u1ByRLJe2pOwTNPtKMWmN3CNbCfJVZa%2BopBFucNoVaw%3D&reserved=0> or Android<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7C3fe5ad8738384ffe782c08da058aac53%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637828390402636246%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=DBqEtVliPcU8MPUPvppbUgPiwWHKqptux%2BswNf79yJc%3D&reserved=0>.

**Comment by snowformatics** [comment]
Thanks Carl, I used Tassel to convert the file and it worked very well!
