### ISSUE TITLE
Run without PLINK format

### ISSUE THREAD

**Issue by snowformatics** [fastlmm/FaST-LMM#30]
Hi,

I have a short question, is it possible to run FaST-LMM without PLINK Bed format? If I understand correctly, single_snp function run with any SnpReader format which could be also SnpData. Is this correct? What about the FAM and BIM file, are there required? I want to add an alternative option without using PLINK and work with the VCF directly or often users have only the SNP matrix available.

Thanks 
Stefanie

**Comment by CarlKCarlK** [comment]
Yes,

FaST-LMM is just as happy to run on a "SnpData" as on a "Bed".

Here is a simple example of creating a tiny SnpData object:

from pysnptools.snpreader import SnpData
>>> snpdata = SnpData(iid=[['fam0','iid0'],['fam0','iid1']], sid=['snp334','snp349','snp921'], val=[[0.,2.,0.],[0.,1.,2.]])
>>> print((snpdata.val[0,1], snpdata.iid_count, snpdata.sid_count))
(2.0, 2, 3)

You'll notice that you pass "SnpData(...)" a list of family/individual id names, a list of SNP names, and a 2D array of values. In this case, the SnpData was created without chromosome information, so it defaults to chromosome "0". You can change this with an additional line:

snpdata.pos[:,0] = [1,1,2] # assign the first and 2nd SNP to chrom 1 and 3rd to chrom 2

There is more info at: https://fastlmm.github.io/PySnpTools/#snpreader-snpdata

Put another way - If you can write Python code that gets this information from VCF files (or any other format):

  *   Family and SNP ids
  *   SNP ids
  *   Chromosome number
  *   A 2-D array of values 0,1,2 and missing (representing the allele count)
Then you can create a SnpData and then you can call FaST-LMM.

If you can extract this info from your VCF files (or any other sources), I'm happy to help you get FaST-LMM running on this info.


  *   Carl


From: snowformatics ***@***.***>
Sent: Monday, August 01, 2022 12:37 AM
To: fastlmm/FaST-LMM ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [fastlmm/FaST-LMM] Run without PLINK format (Issue #30)
Importance: High


Hi,

I have a short question, is it possible to run FaST-LMM without PLINK Bed format? If I understand correctly, single_snp function run with any SnpReader format which could be also SnpData. Is this correct? What about the FAM and BIM file, are there required? I want to add an alternative option without using PLINK and work with the VCF directly or often users have only the SNP matrix available.

Thanks
Stefanie

-

**Comment by snowformatics** [comment]
Hi Carl,

Thanks, good news! I will extract the necessary data and try it out. I will
inform you then.

Stefanie

Am Mo., 1. Aug. 2022 um 19:53 Uhr schrieb Carl Kadie <
***@***.***>:
