### ISSUE TITLE
 Ill-formed BED file. BED file header is incorrect or length is wrong

### ISSUE THREAD

**Issue by snowformatics** [fastlmm/FaST-LMM#31]
Hi everyone,

I converted as usual my VCF file to Bed (PLINK2). FaST-LMM reports this error:

 "Ill-formed BED file. BED file header is incorrect or length is wrong."

Any ideas what could cause this error? I checked the VCF file and it looks fine to me. With other VCF converted BED files I have no problems...

Thanks
Stefanie

**Comment by CarlKCarlK** [comment]
Stefanie,

How did you convert your VCF to Bed (Plink2)?


  *   Carl

From: snowformatics ***@***.***>
Sent: Monday, August 08, 2022 1:33 AM
To: fastlmm/FaST-LMM ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [fastlmm/FaST-LMM] Ill-formed BED file. BED file header is incorrect or length is wrong (Issue #31)
Importance: High


Hi everyone,

I converted as usual my VCF file to Bed (PLINK2). FaST-LMM reports this error:

"Ill-formed BED file. BED file header is incorrect or length is wrong."

Any ideas what could cause this error? I checked the VCF file and it looks fine to me. With other VCF converted BED files I have no problems...

Thanks
Stefanie

-

**Comment by snowformatics** [comment]
Hi Carl,

Yes as usually, no error in the logs. Everything looks fine…



Carl Kadie ***@***.***> schrieb am Mo. 8. Aug. 2022 um 16:41:

**Comment by CarlKCarlK** [comment]
Stefanie,

FaST-LMM understand only PLINK 1.9, but not PLINK 2.


  *   Carl

**Comment by snowformatics** [comment]
Hi Carl,

that's very funny because I am using PLINK2 formatted BED files since months (about 10 different VCF files), I checked again. Using PLINK 1.9 solved the problem and error message above. So it looks like it depends on the VCF file.

Thanks a lot!
Stefanie
