### ISSUE TITLE
Replacement for fastlmm.util.stats.quadform?

### ISSUE THREAD

**Issue by yyang-peko** [fastlmm/FaST-LMM#33]
I'm using another package that uses quadform from the original FaST-LMM

import fastlmm.util.stats.quadform as qf
def davies(self, squaredform, eigvals, acc):
        return qf.qf(squaredform, eigvals, acc=acc)[0]

What's the appropriate replacement for the current version?

**Comment by CarlKCarlK** [comment]
Greetings,

Thanks for using parts of FaST-LMM!

Please try this:

pip install fastlmmclib<https://github.com/fastlmm/fastlmmclib>

Then, in Python:
import fastlmmclib.quadform as qf

Yours,
Carl


Carl Kadie, Ph.D.
FaST-LMM & PySnpTools Team<https://fastlmm.github.io/>
(Microsoft Research, retired)
https://www.linkedin.com/in/carlk/

Join the FaST-LMM user discussion and announcement list via ***@***.***?subject=Subscribe> (or use web sign up<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fmail.python.org%2Fmailman3%2Flists%2Ffastlmm-user.python.org&data=02%7C01%7C%7C13a5c33d7cd84cad5cdf08d7bba56e20%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637184191498409587&sdata=2CQWjQEwOpQol2rQ1eoyVTgY8WvInV8UH31Wtl68FzY%3D&reserved=0>)

From: YYang ***@***.***>
Sent: Thursday, January 26, 2023 10:09 AM
To: fastlmm/FaST-LMM ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [fastlmm/FaST-LMM] Replacement for fastlmm.util.stats.quadform? (Issue #33)
Importance: High


I'm using another package that uses quadform from the original FaST-LMM

import fastlmm.util.stats.quadform as qf
def davies(self, squaredform, eigvals, acc):
return qf.qf(squaredform, eigvals, acc=acc)[0]

What's the appropriate replacement for the current version?

-
