### ISSUE TITLE
FloatingPointError: divide by zero encountered in true_divide

### ISSUE THREAD

**Issue by zhaouu** [fastlmm/FaST-LMM#34]
Hi Carl,
we are trying to run GWAS using single_snp function, but I encountered a FloatingPointError, I also tried to randomly extract 15000 snps from bed file, using the same phenotype file, the randomly extracted file works fine, but the whole  snps file encountered a FloatingPointError, I don't know if there is a solution.

```/public/home/hzhao/anaconda3/envs/fastlmm_py3/lib/python3.7/site-packages/fastlmm/inference/lmm_cov.py:1038: RuntimeWarning: invalid value encountered in true_divide
  beta = snpsKY / (snpsKsnps + penalty_)
---------------------------------------------------------------------------
FloatingPointError                        Traceback (most recent call last)
<ipython-input-45-9953d88378d2> in <module>
      1 from fastlmm.association import single_snp
----> 2 lmm_df = single_snp(test_snps=res.snp_data,pheno='/public/home/hzhao/data/Hybrid_panicle/GWAS/Pheno/Apop_yied.txt', covar=None, K0 = None, count_A1= False, leave_out_one_chrom=True, GB_goal=50, show_snp_fract_var_exp=True)

~/anaconda3/envs/fastlmm_py3/lib/python3.7/site-packages/fastlmm/association/single_snp.py in single_snp(test_snps, pheno, K0, K1, mixing, covar, covar_by_chrom, leave_out_one_chrom, output_file_name, h2, log_delta, show_snp_fract_var_exp, cache_file, GB_goal, interact_with_snp, force_full_rank, force_low_rank, G0, G1, runner, map_reduce_outer, pvalue_threshold, random_threshold, random_seed, xp, count_A1)
    386                     output_file_name
    387                 ),
--> 388                 runner=runner_outer,
    389             )
    390 

~/anaconda3/envs/fastlmm_py3/lib/python3.7/site-packages/pysnptools/util/mapreduce1/mapreduce.py in map_reduce(input_seq, mapper, reducer, input_files, output_files, name, runner, nested)
    200         runner = Local()
    201 
--> 202     result = runner.run(dist)
    203     return result
    204 

~/anaconda3/envs/fastlmm_py3/lib/python3.7/site-packages/pysnptools/util/mapreduce1/runner/local.py in run(self, distributable)
     46         _JustCheckExists().input(distributable)
     47         with patch.dict('os.environ', {'MKL_NUM_THREADS': str(self.mkl_num_threads)} if self.mkl_num_threads is not None else {}) as _:
---> 48             result = _run_all_in_memory(distributable)
     49         _JustCheckExists().output(distributable)
     50         return result

~/anaconda3/envs/fastlmm_py3/lib/python3.7/site-packages/pysnptools/util/mapreduce1/runner/__init__.py in _run_all_in_memory(work)
     32         work_sequence = work.work_sequence()
     33         result_sequence = work_sequence_to_result_sequence(work_sequence)
---> 34         return work.reduce(result_sequence)
     35 
     36 

~/anaconda3/envs/fastlmm_py3/lib/python3.7/site-packages/pysnptools/util/mapreduce1/mapreduce.py in reduce(self, output_seq)
     75         '''
     76 
---> 77         return self.reducer(output_seq)
     78 
     79 

~/anaconda3/envs/fastlmm_py3/lib/python3.7/site-packages/fastlmm/association/single_snp.py in reducer_closure(frame_sequence)
    365 
    366             def reducer_closure(frame_sequence):
--> 367                 frame = pd.concat(frame_sequence)
    368                 frame.sort_values(by="PValue", inplace=True)
    369                 frame.index = np.arange(len(frame))

~/anaconda3/envs/fastlmm_py3/lib/python3.7/site-packages/pandas/util/_decorators.py in wrapper(*args, **kwargs)
    309                     stacklevel=stacklevel,
    310                 )
--> 311             return func(*args, **kwargs)
    312 
    313         return wrapper

~/anaconda3/envs/fastlmm_py3/lib/python3.7/site-packages/pandas/core/reshape/concat.py in concat(objs, axis, join, ignore_index, keys, levels, names, verify_integrity, sort, copy)
    302         verify_integrity=verify_integrity,
    303         copy=copy,
--> 304         sort=sort,
    305     )
    306 

~/anaconda3/envs/fastlmm_py3/lib/python3.7/site-packages/pandas/core/reshape/concat.py in __init__(self, objs, axis, join, keys, levels, names, ignore_index, verify_integrity, copy, sort)
    346             objs = [objs[k] for k in keys]
    347         else:
--> 348             objs = list(objs)
    349 
    350         if len(objs) == 0:

~/anaconda3/envs/fastlmm_py3/lib/python3.7/site-packages/pysnptools/util/mapreduce1/runner/__init__.py in work_sequence_to_result_sequence(work_sequence)
     13     for work in work_sequence:
     14         if callable(work):
---> 15             result = work()
     16         else:
     17             result = _run_all_in_memory(work)

~/anaconda3/envs/fastlmm_py3/lib/python3.7/site-packages/pysnptools/util/mapreduce1/mapreduce.py in <lambda>(i, input_arg)
     63                 #logging.debug("\nexecuting %i" % i)
     64                 with _MapReduce._dyn_vars(is_in_nested=False):
---> 65                     yield lambda i=i, input_arg=input_arg: self.dowork(i, input_arg)  # the 'i=i',etc is need to get around a strangeness in Python
     66             else:
     67                 assert self.nested is not None, "real assert"

~/anaconda3/envs/fastlmm_py3/lib/python3.7/site-packages/pysnptools/util/mapreduce1/mapreduce.py in dowork(self, i, input_arg)
     90         #logging.debug("\nexecuting {0}".format(input_arg))
     91         work = lambda : self.mapper(input_arg)
---> 92         result = _run_all_in_memory(work)
     93         return result
     94 

~/anaconda3/envs/fastlmm_py3/lib/python3.7/site-packages/pysnptools/util/mapreduce1/runner/__init__.py in _run_all_in_memory(work)
     25     """
     26     if callable(work):
---> 27         return work()
     28     else:
     29         assert hasattr(

~/anaconda3/envs/fastlmm_py3/lib/python3.7/site-packages/pysnptools/util/mapreduce1/mapreduce.py in <lambda>()
     89         #logging.info("{0}, {1}".format(len(train_snp_idx), len(test_snp_idx)))
     90         #logging.debug("\nexecuting {0}".format(input_arg))
---> 91         work = lambda : self.mapper(input_arg)
     92         result = _run_all_in_memory(work)
     93         return result

~/anaconda3/envs/fastlmm_py3/lib/python3.7/site-packages/fastlmm/association/single_snp.py in nested_closure(chrom)
    360                     random_threshold=random_threshold,
    361                     random_seed=random_seed,
--> 362                     xp=xp,
    363                 )
    364                 return distributable

~/anaconda3/envs/fastlmm_py3/lib/python3.7/site-packages/fastlmm/association/single_snp.py in _internal_single(K0, test_snps, pheno, covar, K1, mixing, h2, log_delta, show_snp_fract_var_exp, cache_file, force_full_rank, force_low_rank, output_file_name, block_size, interact_with_snp, runner, pvalue_threshold, random_threshold, random_seed, xp)
    953         random_threshold,
    954         random_seed,
--> 955         show_snp_fract_var_exp,
    956     )
    957 

~/anaconda3/envs/fastlmm_py3/lib/python3.7/site-packages/fastlmm/association/single_snp.py in _snp_tester(test_snps, interact, pheno, lmm, block_size, output_file_name, runner, h2, mixing, pvalue_threshold, random_threshold, random_seed, show_snp_fract_var_exp)
   1379         output_files=[output_file_name],
   1380         name="single_snp(output_file={0})".format(output_file_name),
-> 1381         runner=runner,
   1382     )
   1383     return frame

~/anaconda3/envs/fastlmm_py3/lib/python3.7/site-packages/pysnptools/util/mapreduce1/mapreduce.py in map_reduce(input_seq, mapper, reducer, input_files, output_files, name, runner, nested)
    200         runner = Local()
    201 
--> 202     result = runner.run(dist)
    203     return result
    204 

~/anaconda3/envs/fastlmm_py3/lib/python3.7/site-packages/pysnptools/util/mapreduce1/runner/local.py in run(self, distributable)
     46         _JustCheckExists().input(distributable)
     47         with patch.dict('os.environ', {'MKL_NUM_THREADS': str(self.mkl_num_threads)} if self.mkl_num_threads is not None else {}) as _:
---> 48             result = _run_all_in_memory(distributable)
     49         _JustCheckExists().output(distributable)
     50         return result

~/anaconda3/envs/fastlmm_py3/lib/python3.7/site-packages/pysnptools/util/mapreduce1/runner/__init__.py in _run_all_in_memory(work)
     32         work_sequence = work.work_sequence()
     33         result_sequence = work_sequence_to_result_sequence(work_sequence)
---> 34         return work.reduce(result_sequence)
     35 
     36 

~/anaconda3/envs/fastlmm_py3/lib/python3.7/site-packages/pysnptools/util/mapreduce1/mapreduce.py in reduce(self, output_seq)
     75         '''
     76 
---> 77         return self.reducer(output_seq)
     78 
     79 

~/anaconda3/envs/fastlmm_py3/lib/python3.7/site-packages/fastlmm/association/single_snp.py in reducer_closure(result_sequence)
   1363             create_directory_if_necessary(output_file_name)
   1364 
-> 1365         frame = pd.concat(result_sequence)
   1366         frame.sort_values(by="PValue", inplace=True)
   1367         frame.index = np.arange(len(frame))

~/anaconda3/envs/fastlmm_py3/lib/python3.7/site-packages/pandas/util/_decorators.py in wrapper(*args, **kwargs)
    309                     stacklevel=stacklevel,
    310                 )
--> 311             return func(*args, **kwargs)
    312 
    313         return wrapper

~/anaconda3/envs/fastlmm_py3/lib/python3.7/site-packages/pandas/core/reshape/concat.py in concat(objs, axis, join, ignore_index, keys, levels, names, verify_integrity, sort, copy)
    302         verify_integrity=verify_integrity,
    303         copy=copy,
--> 304         sort=sort,
    305     )
    306 

~/anaconda3/envs/fastlmm_py3/lib/python3.7/site-packages/pandas/core/reshape/concat.py in __init__(self, objs, axis, join, keys, levels, names, ignore_index, verify_integrity, copy, sort)
    346             objs = [objs[k] for k in keys]
    347         else:
--> 348             objs = list(objs)
    349 
    350         if len(objs) == 0:

~/anaconda3/envs/fastlmm_py3/lib/python3.7/site-packages/pysnptools/util/mapreduce1/runner/__init__.py in work_sequence_to_result_sequence(work_sequence)
     13     for work in work_sequence:
     14         if callable(work):
---> 15             result = work()
     16         else:
     17             result = _run_all_in_memory(work)

~/anaconda3/envs/fastlmm_py3/lib/python3.7/site-packages/pysnptools/util/mapreduce1/mapreduce.py in <lambda>(i, input_arg)
     63                 #logging.debug("\nexecuting %i" % i)
     64                 with _MapReduce._dyn_vars(is_in_nested=False):
---> 65                     yield lambda i=i, input_arg=input_arg: self.dowork(i, input_arg)  # the 'i=i',etc is need to get around a strangeness in Python
     66             else:
     67                 assert self.nested is not None, "real assert"

~/anaconda3/envs/fastlmm_py3/lib/python3.7/site-packages/pysnptools/util/mapreduce1/mapreduce.py in dowork(self, i, input_arg)
     90         #logging.debug("\nexecuting {0}".format(input_arg))
     91         work = lambda : self.mapper(input_arg)
---> 92         result = _run_all_in_memory(work)
     93         return result
     94 

~/anaconda3/envs/fastlmm_py3/lib/python3.7/site-packages/pysnptools/util/mapreduce1/runner/__init__.py in _run_all_in_memory(work)
     25     """
     26     if callable(work):
---> 27         return work()
     28     else:
     29         assert hasattr(

~/anaconda3/envs/fastlmm_py3/lib/python3.7/site-packages/pysnptools/util/mapreduce1/mapreduce.py in <lambda>()
     89         #logging.info("{0}, {1}".format(len(train_snp_idx), len(test_snp_idx)))
     90         #logging.debug("\nexecuting {0}".format(input_arg))
---> 91         work = lambda : self.mapper(input_arg)
     92         result = _run_all_in_memory(work)
     93         return result

~/anaconda3/envs/fastlmm_py3/lib/python3.7/site-packages/fastlmm/association/single_snp.py in mapper_closure(work_index)
   1329             snps=variables_to_test,
   1330             Sd=Sd,
-> 1331             denom=denom,
   1332         )
   1333 

~/anaconda3/envs/fastlmm_py3/lib/python3.7/site-packages/fastlmm/inference/lmm_cov.py in nLLeval(self, h2, logdelta, delta, dof, scale, penalty, snps, Usnps, UUsnps, UW, UUW, weightW, idx_pheno, Sd, denom)
    837             Usnps=Usnps,
    838             UUsnps=UUsnps,
--> 839             idx_pheno=idx_pheno,
    840         )
    841         result["h2"] = h2

~/anaconda3/envs/fastlmm_py3/lib/python3.7/site-packages/fastlmm/inference/lmm_cov.py in nLLcore(self, Sd, dof, scale, penalty, UW, UUW, weightW, denom, Usnps, UUsnps, idx_pheno)
   1055                 )
   1056             else:
-> 1057                 variance_beta = r2 / (N - 1.0) / snpsKsnps
   1058                 fraction_variance_explained_beta = (
   1059                     variance_explained_beta / YKY[np.newaxis, :]

FloatingPointError: divide by zero encountered in true_divide

**Comment by CarlKCarlK** [comment]
Hu Zhao,

Thanks for using FaST-LMM! If you like, you can email me directly at ***@***.******@***.***>.

I have to be away for a few hours but should be able to look into this more when I return. Some questions/ideas:


  *   What is your number of individuals and SNPs?
  *   How many phenotypes to you have?
  *   How many chromosomes does your data have?
  *   Can you try running with leave_out_one_chrom=False and seeing if you get the error. (This wouldn't be for your final run, but for debugging it could make things faster.)
  *   How long does it run before it gets the error?
  *   Can you increase the number of randomly chosen SNPs from 15K to 30K, 100K, ...until you hit the error.
  *   If you leave off GB_goal=50 does it change anything? (It shouldn't matter, but I'm looking at all the non-default settings).

Thanks again for using FaST-LMM. I'm sure we'll be able to figure this out.


  *   Carl


Carl Kadie, Ph.D.
FaST-LMM & PySnpTools Team<https://fastlmm.github.io/>
(Microsoft Research, retired)
https://www.linkedin.com/in/carlk/
Join the FaST-LMM user discussion and announcement list via ***@***.***?subject=Subscribe> (or use web sign up<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fmail.python.org%2Fmailman3%2Flists%2Ffastlmm-user.python.org&data=02%7C01%7C%7C13a5c33d7cd84cad5cdf08d7bba56e20%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637184191498409587&sdata=2CQWjQEwOpQol2rQ1eoyVTgY8WvInV8UH31Wtl68FzY%3D&reserved=0>

From: Hu Zhao ***@***.***>
Sent: Friday, January 27, 2023 3:34 AM
To: fastlmm/FaST-LMM ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [fastlmm/FaST-LMM] FloatingPointError: divide by zero encountered in true_divide (Issue #34)
Importance: High


Hi Carl,
we are trying to run GWAS using single_snp function, but I encountered a FloatingPointError, I also tried to randomly extract 15000 snps from bed file, using the same phenotype file, the randomly extracted file works fine, but the whole snps file encountered a FloatingPointError, I don't know if there is a solution.

  beta = snpsKY / (snpsKsnps + penalty_)

---------------------------------------------------------------------------

FloatingPointError                        Traceback (most recent call last)

<ipython-input-45-9953d88378d2> in <module>

      1 from fastlmm.association import single_snp

----> 2 lmm_df = single_snp(test_snps=res.snp_data,pheno='/public/home/hzhao/data/Hybrid_panicle/GWAS/Pheno/Apop_yied.txt', covar=None, K0 = None, count_A1= False, leave_out_one_chrom=True, GB_goal=50, show_snp_fract_var_exp=True)



~/anaconda3/envs/fastlmm_py3/lib/python3.7/site-packages/fastlmm/association/single_snp.py in single_snp(test_snps, pheno, K0, K1, mixing, covar, covar_by_chrom, leave_out_one_chrom, output_file_name, h2, log_delta, show_snp_fract_var_exp, cache_file, GB_goal, interact_with_snp, force_full_rank, force_low_rank, G0, G1, runner, map_reduce_outer, pvalue_threshold, random_threshold, random_seed, xp, count_A1)

    386                     output_file_name

    387                 ),

--> 388                 runner=runner_outer,

    389             )

    390



~/anaconda3/envs/fastlmm_py3/lib/python3.7/site-packages/pysnptools/util/mapreduce1/mapreduce.py in map_reduce(input_seq, mapper, reducer, input_files, output_files, name, runner, nested)

    200         runner = Local()

    201

--> 202     result = runner.run(dist)

    203     return result

    204



~/anaconda3/envs/fastlmm_py3/lib/python3.7/site-packages/pysnptools/util/mapreduce1/runner/local.py in run(self, distributable)

     46         _JustCheckExists().input(distributable)

     47         with patch.dict('os.environ', {'MKL_NUM_THREADS': str(self.mkl_num_threads)} if self.mkl_num_threads is not None else {}) as _:

---> 48             result = _run_all_in_memory(distributable)

     49         _JustCheckExists().output(distributable)

     50         return result



~/anaconda3/envs/fastlmm_py3/lib/python3.7/site-packages/pysnptools/util/mapreduce1/runner/__init__.py in _run_all_in_memory(work)

     32         work_sequence = work.work_sequence()

     33         result_sequence = work_sequence_to_result_sequence(work_sequence)

---> 34         return work.reduce(result_sequence)

     35

     36



~/anaconda3/envs/fastlmm_py3/lib/python3.7/site-packages/pysnptools/util/mapreduce1/mapreduce.py in reduce(self, output_seq)

     75         '''

     76

---> 77         return self.reducer(output_seq)

     78

     79



~/anaconda3/envs/fastlmm_py3/lib/python3.7/site-packages/fastlmm/association/single_snp.py in reducer_closure(frame_sequence)

    365

    366             def reducer_closure(frame_sequence):

--> 367                 frame = pd.concat(frame_sequence)

    368                 frame.sort_values(by="PValue", inplace=True)

    369                 frame.index = np.arange(len(frame))



~/anaconda3/envs/fastlmm_py3/lib/python3.7/site-packages/pandas/util/_decorators.py in wrapper(*args, **kwargs)

    309                     stacklevel=stacklevel,

    310                 )

--> 311             return func(*args, **kwargs)

    312

    313         return wrapper



~/anaconda3/envs/fastlmm_py3/lib/python3.7/site-packages/pandas/core/reshape/concat.py in concat(objs, axis, join, ignore_index, keys, levels, names, verify_integrity, sort, copy)

    302         verify_integrity=verify_integrity,

    303         copy=copy,

--> 304         sort=sort,

    305     )

    306



~/anaconda3/envs/fastlmm_py3/lib/python3.7/site-packages/pandas/core/reshape/concat.py in __init__(self, objs, axis, join, keys, levels, names, ignore_index, verify_integrity, copy, sort)

    346             objs = [objs[k] for k in keys]

    347         else:

--> 348             objs = list(objs)

    349

    350         if len(objs) == 0:



~/anaconda3/envs/fastlmm_py3/lib/python3.7/site-packages/pysnptools/util/mapreduce1/runner/__init__.py in work_sequence_to_result_sequence(work_sequence)

     13     for work in work_sequence:

     14         if callable(work):

---> 15             result = work()

     16         else:

     17             result = _run_all_in_memory(work)



~/anaconda3/envs/fastlmm_py3/lib/python3.7/site-packages/pysnptools/util/mapreduce1/mapreduce.py in <lambda>(i, input_arg)

     63                 #logging.debug("\nexecuting %i" % i)

     64                 with _MapReduce._dyn_vars(is_in_nested=False):

---> 65                     yield lambda i=i, input_arg=input_arg: self.dowork(i, input_arg)  # the 'i=i',etc is need to get around a strangeness in Python

     66             else:

     67                 assert self.nested is not None, "real assert"



~/anaconda3/envs/fastlmm_py3/lib/python3.7/site-packages/pysnptools/util/mapreduce1/mapreduce.py in dowork(self, i, input_arg)

     90         #logging.debug("\nexecuting {0}".format(input_arg))

     91         work = lambda : self.mapper(input_arg)

---> 92         result = _run_all_in_memory(work)

     93         return result

     94



~/anaconda3/envs/fastlmm_py3/lib/python3.7/site-packages/pysnptools/util/mapreduce1/runner/__init__.py in _run_all_in_memory(work)

     25     """

     26     if callable(work):

---> 27         return work()

     28     else:

     29         assert hasattr(



~/anaconda3/envs/fastlmm_py3/lib/python3.7/site-packages/pysnptools/util/mapreduce1/mapreduce.py in <lambda>()

     89         #logging.info("{0}, {1}".format(len(train_snp_idx), len(test_snp_idx)))

     90         #logging.debug("\nexecuting {0}".format(input_arg))

---> 91         work = lambda : self.mapper(input_arg)

     92         result = _run_all_in_memory(work)

     93         return result



~/anaconda3/envs/fastlmm_py3/lib/python3.7/site-packages/fastlmm/association/single_snp.py in nested_closure(chrom)

    360                     random_threshold=random_threshold,

    361                     random_seed=random_seed,

--> 362                     xp=xp,

    363                 )

    364                 return distributable



~/anaconda3/envs/fastlmm_py3/lib/python3.7/site-packages/fastlmm/association/single_snp.py in _internal_single(K0, test_snps, pheno, covar, K1, mixing, h2, log_delta, show_snp_fract_var_exp, cache_file, force_full_rank, force_low_rank, output_file_name, block_size, interact_with_snp, runner, pvalue_threshold, random_threshold, random_seed, xp)

    953         random_threshold,

    954         random_seed,

--> 955         show_snp_fract_var_exp,

    956     )

    957



~/anaconda3/envs/fastlmm_py3/lib/python3.7/site-packages/fastlmm/association/single_snp.py in _snp_tester(test_snps, interact, pheno, lmm, block_size, output_file_name, runner, h2, mixing, pvalue_threshold, random_threshold, random_seed, show_snp_fract_var_exp)

   1379         output_files=[output_file_name],

   1380         name="single_snp(output_file={0})".format(output_file_name),

-> 1381         runner=runner,

   1382     )

   1383     return frame



~/anaconda3/envs/fastlmm_py3/lib/python3.7/site-packages/pysnptools/util/mapreduce1/mapreduce.py in map_reduce(input_seq, mapper, reducer, input_files, output_files, name, runner, nested)

    200         runner = Local()

    201

--> 202     result = runner.run(dist)

    203     return result

    204



~/anaconda3/envs/fastlmm_py3/lib/python3.7/site-packages/pysnptools/util/mapreduce1/runner/local.py in run(self, distributable)

     46         _JustCheckExists().input(distributable)

     47         with patch.dict('os.environ', {'MKL_NUM_THREADS': str(self.mkl_num_threads)} if self.mkl_num_threads is not None else {}) as _:

---> 48             result = _run_all_in_memory(distributable)

     49         _JustCheckExists().output(distributable)

     50         return result



~/anaconda3/envs/fastlmm_py3/lib/python3.7/site-packages/pysnptools/util/mapreduce1/runner/__init__.py in _run_all_in_memory(work)

     32         work_sequence = work.work_sequence()

     33         result_sequence = work_sequence_to_result_sequence(work_sequence)

---> 34         return work.reduce(result_sequence)

     35

     36



~/anaconda3/envs/fastlmm_py3/lib/python3.7/site-packages/pysnptools/util/mapreduce1/mapreduce.py in reduce(self, output_seq)

     75         '''

     76

---> 77         return self.reducer(output_seq)

     78

     79



~/anaconda3/envs/fastlmm_py3/lib/python3.7/site-packages/fastlmm/association/single_snp.py in reducer_closure(result_sequence)

   1363             create_directory_if_necessary(output_file_name)

   1364

-> 1365         frame = pd.concat(result_sequence)

   1366         frame.sort_values(by="PValue", inplace=True)

   1367         frame.index = np.arange(len(frame))



~/anaconda3/envs/fastlmm_py3/lib/python3.7/site-packages/pandas/util/_decorators.py in wrapper(*args, **kwargs)

    309                     stacklevel=stacklevel,

    310                 )

--> 311             return func(*args, **kwargs)

    312

    313         return wrapper



~/anaconda3/envs/fastlmm_py3/lib/python3.7/site-packages/pandas/core/reshape/concat.py in concat(objs, axis, join, ignore_index, keys, levels, names, verify_integrity, sort, copy)

    302         verify_integrity=verify_integrity,

    303         copy=copy,

--> 304         sort=sort,

    305     )

    306



~/anaconda3/envs/fastlmm_py3/lib/python3.7/site-packages/pandas/core/reshape/concat.py in __init__(self, objs, axis, join, keys, levels, names, ignore_index, verify_integrity, copy, sort)

    346             objs = [objs[k] for k in keys]

    347         else:

--> 348             objs = list(objs)

    349

    350         if len(objs) == 0:



~/anaconda3/envs/fastlmm_py3/lib/python3.7/site-packages/pysnptools/util/mapreduce1/runner/__init__.py in work_sequence_to_result_sequence(work_sequence)

     13     for work in work_sequence:

     14         if callable(work):

---> 15             result = work()

     16         else:

     17             result = _run_all_in_memory(work)



~/anaconda3/envs/fastlmm_py3/lib/python3.7/site-packages/pysnptools/util/mapreduce1/mapreduce.py in <lambda>(i, input_arg)

     63                 #logging.debug("\nexecuting %i" % i)

     64                 with _MapReduce._dyn_vars(is_in_nested=False):

---> 65                     yield lambda i=i, input_arg=input_arg: self.dowork(i, input_arg)  # the 'i=i',etc is need to get around a strangeness in Python

     66             else:

     67                 assert self.nested is not None, "real assert"



~/anaconda3/envs/fastlmm_py3/lib/python3.7/site-packages/pysnptools/util/mapreduce1/mapreduce.py in dowork(self, i, input_arg)

     90         #logging.debug("\nexecuting {0}".format(input_arg))

     91         work = lambda : self.mapper(input_arg)

---> 92         result = _run_all_in_memory(work)

     93         return result

     94



~/anaconda3/envs/fastlmm_py3/lib/python3.7/site-packages/pysnptools/util/mapreduce1/runner/__init__.py in _run_all_in_memory(work)

     25     """

     26     if callable(work):

---> 27         return work()

     28     else:

     29         assert hasattr(



~/anaconda3/envs/fastlmm_py3/lib/python3.7/site-packages/pysnptools/util/mapreduce1/mapreduce.py in <lambda>()

     89         #logging.info("{0}, {1}".format(len(train_snp_idx), len(test_snp_idx)))

     90         #logging.debug("\nexecuting {0}".format(input_arg))

---> 91         work = lambda : self.mapper(input_arg)

     92         result = _run_all_in_memory(work)

     93         return result



~/anaconda3/envs/fastlmm_py3/lib/python3.7/site-packages/fastlmm/association/single_snp.py in mapper_closure(work_index)

   1329             snps=variables_to_test,

   1330             Sd=Sd,

-> 1331             denom=denom,

   1332         )

   1333



~/anaconda3/envs/fastlmm_py3/lib/python3.7/site-packages/fastlmm/inference/lmm_cov.py in nLLeval(self, h2, logdelta, delta, dof, scale, penalty, snps, Usnps, UUsnps, UW, UUW, weightW, idx_pheno, Sd, denom)

    837             Usnps=Usnps,

    838             UUsnps=UUsnps,

--> 839             idx_pheno=idx_pheno,

    840         )

    841         result["h2"] = h2



~/anaconda3/envs/fastlmm_py3/lib/python3.7/site-packages/fastlmm/inference/lmm_cov.py in nLLcore(self, Sd, dof, scale, penalty, UW, UUW, weightW, denom, Usnps, UUsnps, idx_pheno)

   1055                 )

   1056             else:

-> 1057                 variance_beta = r2 / (N - 1.0) / snpsKsnps

   1058                 fraction_variance_explained_beta = (

   1059                     variance_explained_beta / YKY[np.newaxis, :]



FloatingPointError: divide by zero encountered in true_divide

-

**Comment by zhaouu** [comment]
Dear Carl,

Thank you very much for your attentive and timely reply.
I performed GWAS by randomly selecting snps and found that the presence of possibly some snps could cause errors in the program.
I found the erroneous bed file by randomly selecting 1000 snps multiple times.
You can download the test file through this link: https://drive.google.com/file/d/1wX3GjIkegqf2qavxTN81H7GoD5aC125S/view?usp=sharing
Also, I tested every snp in that file and found that 382th snp's exist to get that error. However by checking the genotype, I did not find any difference between this site and the other sites.

```from pysnptools.snpreader import Bed
snp_data = Bed('/public/home/hzhao/data/Hybrid_panicle/GWAS/Bed/test',count_A1=False)
idx=[382]
lmm_df = single_snp(test_snps=snp_data[:,idx], pheno='/public/home/hzhao/data/Hybrid_panicle/GWAS/Pheno/Apop_yied.txt', covar=None, K0 = None, count_A1= False, leave_out_one_chrom=True, show_snp_fract_var_exp=True)

**Comment by CarlKCarlK** [comment]
I've sent a request for data access via Google Drive
