### ISSUE TITLE
[Feature Request] Allow string as chromosom names

### ISSUE THREAD

**Issue by snowformatics** [fastlmm/FaST-LMM#36]
Hi,

it would be great if fast-lmm would work with strings as chromosomes names and map them internally. I am currently mapping the names of the BIM file to integers and store the processed BIM file. After the run I map the ids back and override the BIM.

Would be very convenient and nice to have feature.

Thanks
Stefanie

**Comment by CarlKCarlK** [comment]
Stefanie,

I think there is a feature of bed-reader that may help. See https://fastlmm.github.io/PySnpTools/#pysnptools.snpreader.Bed for some details.

Specifically, there is an option of Bed(...,chrom_map={...}) where you can specify a mapping from strings to any number. When you do that the chromosome names will be converted to numbers (which Fast-LMM requires) on the fly. This saves you from need to create new BIM files.  The only shortcoming is that the output Pandas dataframe will use the numbers, not the original string chromosome names.

Here is an example, run on a new sample bed file with chromosome names "One", "Two", "Three", "Four", "Five".

from fastlmm.association import epistasis, single_snp
from pysnptools.snpreader import Bed, Pheno
from fastlmm.util import example_file # Download and return local file name

bed_fn = "StringChrom.bed"
bed_reader = Bed(bed_fn, count_A1=True, chrom_map={"One":100, "Two":200, "Three":300, "Four":400, "Five":500})
pheno_fn = example_file("tests/datasets/synth/pheno_10_causals.txt")
cov_fn = example_file("tests/datasets/synth/cov.txt")
pheno = Pheno(pheno_fn)

df_single = single_snp(test_snps=bed_reader, pheno=pheno, covar=cov_fn)
df_single

Produces...

sid_index
SNP
Chr
GenDist
ChrPos
PValue
SnpWeight
SnpWeightSE
EffectSize
Mixing
Nullh2
0
52
snp495_m0_.01m1_.04
500.0
4052.0
4052.0
2.990684e-23
-0.418653
0.040052
7.372565e-03
0
0.451117
1
392
snp1422_m0_.49m1_.5
300.0
2392.0
2392.0
8.251921e-23
0.416495
0.040300
8.252624e-02
0
0.279710
2
650
snp1200_m0_.37m1_.36
300.0
2650.0
2650.0
3.048007e-14
-0.328870
0.042021
5.498609e-02
0
0.279710
...

Does this help?

Carl


From: snowformatics ***@***.***>
Sent: Wednesday, August 2, 2023 6:49 AM
To: fastlmm/FaST-LMM ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [fastlmm/FaST-LMM] [Feature Request] Allow string as chromosom names (Issue #36)
Importance: High


Hi,

it would be great if fast-lmm would work with strings as chromosomes names and map them internally. I am currently mapping the names of the BIM file to integers and store the processed BIM file. After the run I map the ids back and override the BIM.

Would be very convenient and nice to have feature.

Thanks
Stefanie

-

**Comment by snowformatics** [comment]
Hi Carl,

sorry I missed this option, my fault :( It works like charm and no problem for the output data frame, I just can convert the names.

Thanks a lot! 
Stefanie

**Comment by CarlKCarlK** [comment]
No problem. (My favorite bug is one that I've already fixed!)

**Comment by CarlKCarlK** [comment]
By the way, here is how you can change the chrom in the Pandas table:
[I didn't even figure this out myself. I used GitHub co-pilot and Chat GPT 4.]

```
from fastlmm.association import epistasis, single_snp
from pysnptools.snpreader import Bed, Pheno
from fastlmm.util import example_file # Download and return local file name

bed_fn = "StringChrom.bed"
chrom_map={"One":100, "Two":200, "Three":300, "Four":400, "Five":500}
bed_reader = Bed(bed_fn, count_A1=True,chrom_map=chrom_map)
pheno_fn = example_file("tests/datasets/synth/pheno_10_causals.txt")
cov_fn = example_file("tests/datasets/synth/cov.txt")
pheno = Pheno(pheno_fn)

df_single = single_snp(test_snps=bed_reader, pheno=pheno, covar=cov_fn)

reversed_chrom_map = {value: key for key, value in chrom_map.items()}
df_single["Chr"] = df_single["Chr"].apply(lambda x: reversed_chrom_map[x])
df_single
```

Outputs:

```
	sid_index	SNP	Chr	GenDist	ChrPos	PValue	SnpWeight	SnpWeightSE	EffectSize	Mixing	Nullh2
0	52	snp495_m0_.01m1_.04	Five	4052.0	4052.0	2.990684e-23	-0.418653	0.040052	7.372565e-03	0	0.451117
1	392	snp1422_m0_.49m1_.5	Three	2392.0	2392.0	8.251921e-23	0.416495	0.040300	8.252624e-02	0	0.279710
2	650	snp1200_m0_.37m1_.36	Three	2650.0	2650.0	3.048007e-14	-0.328870	0.042021	5.498609e-02	0	0.2797
```
