### ISSUE TITLE
Unable to run with multiple phenotypic traits together

### ISSUE THREAD

**Issue by jefflllyyy** [fastlmm/FaST-LMM#37]
Can I analyze multiple phenotypic traits simultaneously? For example, if I input 10 phenotypic traits into a phenotype.txt file and run the program, will it analyze all 10 traits simultaneously? Or do I have to analyze one phenotypic trait at a time?

**Comment by CarlKCarlK** [comment]
Jeff,

Thanks for considering FaST-LMM.

Yes, multiple phenotypes should just work (and with great efficiency). Here is a notebook with an example:
https://nbviewer.org/github/fastlmm/FaST-LMM/blob/master/doc/ipynb/fastlmm2021.ipynb

If you have any issues just let us know.

Yours,
Carl


Carl Kadie, Ph.D.
FaST-LMM & PySnpTools Team<https://fastlmm.github.io/>
(Microsoft Research, retired)
https://www.linkedin.com/in/carlk/

Join the FaST-LMM user discussion and announcement list via ***@***.***?subject=Subscribe> (or use web sign up<https://mail.python.org/mailman3/lists/fastlmm-user.python.org>)

From: JEFF666 ***@***.***>
Sent: Wednesday, January 24, 2024 1:22 AM
To: fastlmm/FaST-LMM ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [fastlmm/FaST-LMM] Unable to run with multiple phenotypic traits together (Issue #37)
Importance: High


Can I analyze multiple phenotypic traits simultaneously? For example, if I input 10 phenotypic traits into a phenotype.txt file and run the program, will it analyze all 10 traits simultaneously? Or do I have to analyze one phenotypic trait at a time?

-
