### ISSUE TITLE
How fastlmm deal with "NA" in covariate file?

### ISSUE THREAD

**Issue by baolichang** [fastlmm/FaST-LMM#4]
Hello: This is not really an issue, but I'm not sure how fastlmm deals with samples with missing covariates? Are the samples still included in the calculation but the missing covariate values are filled in as mean/median of all samples (or through imputation)? Or the samples are dropped out of the analysis?
Thank you!

**Comment by CarlKCarlK** [comment]
Baolichang,

Thanks for using FaSTLMM. Great question and one that I did not know the answer to until I looked into it.


  *   how fastlmm deals with samples with missing covariates?

It doesn't!  Specifically, when I looked at single_snp and single_snp_scale, I  found that any NaN's will end up producing a NaN in the final output.

Work around: Fill missing with the column mean as a pre-processing step

Generate some sample data
import numpy as np
from pysnptools.snpreader import SnpData

#Create a SnpReader for the covariate. Here it is an in-memory SnpData, but could be something like
#  covar = Pheno(filename)

np.random.seed(92392)
covar = SnpData(iid=[('f0','iid0'),('f0','iid2'),('f0','iid3')],
               sid = ['height','weight'],
               val = np.random.random((3,2)))
covar.val[0,0] = np.nan
covar.val[2,1] = np.nan
covar.val

array([[       nan, 0.17374433],

       [0.54600136, 0.52250945],

       [0.87375742,        nan]])

The actual work around that fills in missing

#Assumes covar is a SnpReader, e.g. covar = Pheno(filename)

covar = covar.read(view_ok=True) #Turn the covariate into an in-memory SnpData

#Fill columns with mean

#    See https://stackoverflow.com/questions/18689235/numpy-array-replace-nan-values-with-average-of-columns

inds = np.where(np.isnan(covar.val))

covar.val[inds] = np.take(np.nanmean(covar.val, axis=0), inds[1])

covar.val


array([[0.70987939, 0.17374433],

       [0.54600136, 0.52250945],

       [0.87375742, 0.34812689]])


In contrast, for SNP data, any missing values are filled in with the mean.
For a single phenotype, any individuals with missing values are remove.
single_snp_scale also supports multiple phenotypes. If there are multiple phenotypes and any missing value, it raise an error.

Do you think we should change the code do fill in missing covariates automatically? Or is it safer to just have users to this preprocessing step as needed?


Carl

Carl Kadie, Ph.D.
FaST-LMM & PySnpTools Team
(Microsoft Research, retired)
Join the FaST-LMM user discussion and announcement list via email<mailto:fastlmm-user-join@python.org?subject=Subscribe> (or use web sign up<https://mail.python.org/mailman3/lists/fastlmm-user.python.org>)





________________________________

**Comment by baolichang** [comment]
Hi Carl:
Thank you so much for the detailed reply!

It may make more sense to have the users to decide what to do with the missing values in the covariate file. In addition to filling in with the mean, some may prefer imputation or simply ignore the samples with missing covariates (a waste, but if bias may be introduced by mean/imputation it’s better not to use).

Thanks again for your help!

Bao-Li

**Comment by CarlKCarlK** [comment]
Bao-Li,

Excellent suggestions.
At the very least I’ll add check for missing values and raise a clear error (in single_snp and single_snp_scale).


  *   Carl
