### ISSUE TITLE
AttributeError; scipy vs numpy in utils

### ISSUE THREAD

**Issue by vb-iman** [fastlmm/FaST-LMM#40]
Hello! I have run into issues with running single_snp, specifically due to an error in mingrid.py (e.g. line 132)

evalgrid = SP.arange(minval, maxval + step, step)
               ^^^^^^^^^ 

AttributeError: Module 'scipy' has no attribute 'arange'

I was able to fix this problem by changing SP to np in several places (e.g. SP.arange to np.arange or SP.ones to np.ones)--but I wanted to confirm that my changes are correct and that numpy is the intended module for these functions.

Thank you!

**Comment by CarlKCarlK** [comment]
Thanks for using FaST-LMM!

Sorry you hit this bug. It used to work fine, but scipy changed causing the problem. Switching to numpy is the right solution.
Thanks to your report, we'll fix it the next release of FaST-LMM.

Yours,
Carl

Carl Kadie, Ph.D.
[FaST-LMM & PySnpTools Team](https://fastlmm.github.io/)
(Microsoft Research, retired)
https://www.linkedin.com/in/carlk/
Join the FaST-LMM user discussion and announcement list [via email](mailto:fastlmm-user-join@python.org?subject=Subscribe) (or use [web sign up](https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fmail.python.org%2Fmailman3%2Flists%2Ffastlmm-user.python.org&data=02%7C01%7C%7C13a5c33d7cd84cad5cdf08d7bba56e20%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637184191498409587&sdata=2CQWjQEwOpQol2rQ1eoyVTgY8WvInV8UH31Wtl68FzY%3D&reserved=0))

**Comment by vb-iman** [comment]
Thank you for your quick response!

**Comment by asifzubair** [comment]
Yes, hitting this bug as well. Can you tell a version of scipy for which this works ? Thanks!

**Comment by CarlKCarlK** [comment]
Asif,

Thanks for using FaST-LMM! Sorry you hit this bug. I’m working today on update all of FaST-LMM with respect to scipy and numpy.

I think SciPy 1.10.0 was the last to support scipy.arange.

Yours,
Carl

Carl Kadie, Ph.D.
[FaST-LMM & PySnpTools Team](https://fastlmm.github.io/)
(Microsoft Research, retired)
https://www.linkedin.com/in/carlk/
Join the FaST-LMM user discussion and announcement list [via email](mailto:fastlmm-user-join@python.org?subject=Subscribe) (or use [web sign up](https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fmail.python.org%2Fmailman3%2Flists%2Ffastlmm-user.python.org&data=02%7C01%7C%7C13a5c33d7cd84cad5cdf08d7bba56e20%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637184191498409587&sdata=2CQWjQEwOpQol2rQ1eoyVTgY8WvInV8UH31Wtl68FzY%3D&reserved=0))

**Comment by CarlKCarlK** [comment]
Greetings! Thanks for your bug reports. I have a new beta version of FaST-LMM that should fix all the recent issues with NumPy compatibility, etc.

Please try:
` pip install fastlmm==0.6.8b1`

**Comment by CarlKCarlK** [comment]
Fixed with version 0.6.8
