### ISSUE TITLE
warpedlmm installation

### ISSUE THREAD

**Issue by asifzubair** [fastlmm/FaST-LMM#42]
Hi, in the documentation there is a suggestion to use `warpedlmm` to transform continous variables:
> This version of FaST-LMM is designed for use with randomly ascertained data with Gaussian residuals. If you have case-control data with substantial ascertainment bias, you should first transform your phenotype(s) using [LEAP](https://github.com/omerwe/LEAP) (Weissbrod et al., arXiv 2014). If you are analyzing continuous phenotypes with non-Gaussian residuals, you should first transform your phenotype(s) using [Warped-LMM](https://github.com/PMBio/warpedLMM) (Fusi et al., Nature Commun 2014).

I installed `warpedlmm` but I get the following error when I import it:
```python
>>> import warpedlmm
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/anaconda3/envs/warpedlmm/lib/python3.9/site-packages/warpedlmm/__init__.py", line 18, in <module>
    import testing
ModuleNotFoundError: No module named 'testing'
```
Any comments on how to fix this ? Thanks!

**Comment by CarlKCarlK** [comment]
Greetings,

We don't think that the authors of Warped-LMM are supporting it anymore. However ...


  1.  Last month, a Fast-LMM user in Australia said he got Warped-LMM working for himself in Python 3. If you'd like me to introduce to you him, send me a message (carlk at msn.com).
  2.  Also, last month, FaST-LMM collaborator, David Heckerman, asked the Australian researcher if we could see the marginal distribution of his phenotype (to see if discretization would be practical). If you like, send a plot of your phenotype distribution via email and I'll "forward all" it to David.


  *   Carl
From: Asif Zubair ***@***.***>
Sent: Sunday, April 28, 2024 9:30 PM
To: fastlmm/FaST-LMM ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [fastlmm/FaST-LMM] warpedlmm installation (Issue #42)
Importance: High


Hi, in the documentation there is a suggestion to use warpedlmm to transform continous variables:

This version of FaST-LMM is designed for use with randomly ascertained data with Gaussian residuals. If you have case-control data with substantial ascertainment bias, you should first transform your phenotype(s) using LEAP<https://github.com/omerwe/LEAP> (Weissbrod et al., arXiv 2014). If you are analyzing continuous phenotypes with non-Gaussian residuals, you should first transform your phenotype(s) using Warped-LMM<https://github.com/PMBio/warpedLMM> (Fusi et al., Nature Commun 2014).

I installed warpedlmm but I get the following error when I import it:

>>> import warpedlmm

Traceback (most recent call last):

  File "<stdin>", line 1, in <module>

  File "/opt/anaconda3/envs/warpedlmm/lib/python3.9/site-packages/warpedlmm/__init__.py", line 18, in <module>

    import testing

ModuleNotFoundError: No module named 'testing'

Any comments on how to fix this ? Thanks!

-

**Comment by asifzubair** [comment]
Thank you, @CarlKCarlK , I'll shoot you an email. Yes, I also tried using `2to3` to get this to work, but with little luck. I'd appreciate if the Australian user could share his repo. Thanks!
