### ISSUE TITLE
Filtering on allele frequency and outputting allele frequency in result

### ISSUE THREAD

**Issue by vb-iman** [fastlmm/FaST-LMM#43]
Hello! Thank you again for this great tool. I would like to use the same bim/bed/fam filset as input for FastLMM across many phenotypes that have different subsets of individuals with missing data, which means they can't be run with the multi-phenotype mode without unnecessarily dropping individuals. So, I am looping through each phenotype, and using the same bim/bed/fam inputs. Ideally, I'd like to know the minor or alt allele frequency / count for each test variant in the subset of individuals with non-missing phenotypes that FastLMM keeps in single_snp(), and also filter variants based on this criteria if possible.

Does FastLMM calculate allele frequencies or allele counts for test SNPs in the subset of individuals without missing phenotype data? If so, is there a way to provide this frequency / count info for each test SNP in the single_snp() output? Additionally, is it possible to set a MAF cutoff for single_snp() in the subset of individuals with non-missing data prior to doing the association test?

**Comment by CarlKCarlK** [comment]
Greetings,

I think we can use FaST-LMM's sister library [PySnpTools](https://fastlmm.github.io/PySnpTools/) to do what you want. Here is a script on sample data of about 500 individuals x 71,000 SNPs

```python
# Both my simulated pheno data and bed data containing missing values, but we 
# only filter on missing pheno data. It is about 5% missing.
# NaN indicates missing data in the phenotype files.
# 
# We add MAF and MAF_THRESH columns to the results data frame.
# We compute allele freq on both alleles to find the minor allele freq.
# We don't count missing SNP data in MAF calculation

import numpy as np
from fastlmm.association import single_snp
from pysnptools.snpreader import Bed,Pheno
import pysnptools.util as pstutil

maf_thresh = 0.05

BED_FP = "plink_assoc_geno.bed"
bed = Bed(BED_FP, count_A1=True)
phenos = ["bno", "bwt", "abwt"]
for p in phenos:
    PHENO_FP  = "pheno_" + p + ".pheno"
    pheno = Pheno(PHENO_FP).read()
    assert pheno.sid_count == 1, "Only one phenotype allowed at a time"
    # remove NaNs from phenotype
    pheno = pheno[~np.isnan(pheno.val).any(axis=1),:]
    # Create a view of the bed file with only the iids that are in the phenotype file (and put them same order)
    bed2, pheno = pstutil.intersect_apply([bed, pheno])

    # The Bed file may have missing values. GWAS will later fill those in
    # AFTER standardization with 0. For now, we want to compute MAF
    # without including the missing SNP values. We do that with np.nanmean(...,axis=0)*.5
    allele1_freq = np.nanmean(bed2.read().val,axis=0)*.5
    allele2_freq = 1 - allele1_freq
    maf = np.minimum(allele1_freq,allele2_freq)

    # Consider only SNPs with a MAF above the threshold
    snps_to_keep = maf >= maf_thresh
    bed3 = bed2[:,snps_to_keep]
    maf = maf[snps_to_keep]

    # run GWAS
    results_df = single_snp(bed3, pheno, count_A1=True)

    # add two columns: maf and maf_thresh
    results_df["MAF"] = maf
    results_df["MAF_THRESH"] = maf_thresh

    results_df.to_csv("fastlmm_assoc_max_pheno_" + p + ".tsv", sep="\t", index=False, header=True)
```
    
    -- Carl

**Comment by vb-iman** [comment]
This worked, thank you so much!

**Comment by CarlKCarlK** [comment]
Excellent!
