### ISSUE TITLE
how to calculate phenotypic variance explained

### ISSUE THREAD

**Issue by carrot881216** [fastlmm/FaST-LMM#46]
Hi,

I want to calculate phenotypic variance explained, but i cannot find beta value/effect value in fastlmm result, How do I get this value? Or through what calculation can we obtain the following results?

SnpWeight       SnpWeightSE     EffectSize      Mixing  Nullh2

thanks

**Comment by CarlKCarlK** [comment]
Greetings and thanks for using FaST-LMM!

We believe that the Effect Size output is the same as PVE. Effect size is:

SNPWeight^2 * "raw" test SNP variance / phenotype variance, where
* SNPWeight is the beta for the “standardized test SNP” (where "standardized" means made to have mean 0, stdev 1)
* "raw" means the original test SNP values of “0,1,2” (the count of allele 1 or 2 [it doesn’t matter])
* The phenotype’s original values are used (so, they are not, for example, changed by regressing out the covariates)

-- Carl

Carl Kadie, Ph.D.
[FaST-LMM & PySnpTools Team](https://fastlmm.github.io/)
(Microsoft Research, retired)
https://www.linkedin.com/in/carlk/
Join the FaST-LMM user discussion and announcement list [via email](mailto:fastlmm-user-join@python.org?subject=Subscribe) (or use [web sign up](https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fmail.python.org%2Fmailman3%2Flists%2Ffastlmm-user.python.org&data=02%7C01%7C%7C13a5c33d7cd84cad5cdf08d7bba56e20%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637184191498409587&sdata=2CQWjQEwOpQol2rQ1eoyVTgY8WvInV8UH31Wtl68FzY%3D&reserved=0))
