### ISSUE TITLE
q-values in single_snp() output?

### ISSUE THREAD

**Issue by Jorge-Hernansanz** [fastlmm/FaST-LMM#47]
Hi,

Does FaST-LMM provide q-values, apart of p-values, when creating the pandas dataframe with *single_snp()* function?

Best,
Jorge

**Comment by CarlKCarlK** [comment]
Jorge,

Thanks as always for using FaST-LMM!

It doesn't offer q-Values directly, but I believe you can compute q-values and append them to the results of a `single_snp` run like so:


```python
import statsmodels.stats.multitest as smm
import pandas as pd

p_values = results_df['PValue']

# Adjust p-values to q-values using the Benjamini-Hochberg procedure
_, q_values, _, _ = smm.multipletests(p_values, alpha=0.05, method='fdr_bh')

# Add q-values to the results dataframe
results_df['QValue'] = q_values
results_df.head(n=10)
```

When I do this with the [example from the notebook](https://github.com/fastlmm/FaST-LMM/blob/master/doc/ipynb/SingleSnpScale.ipynb) , I get:


![image](https://github.com/fastlmm/FaST-LMM/assets/6549183/1aea9aef-8ec5-45cc-a164-5bec7be68a49)

Please see the [statsmodels documentation](https://www.statsmodels.org/dev/generated/statsmodels.stats.multitest.multipletests.html) to see the options for computing q-values.

-- Carl

**Comment by Jorge-Hernansanz** [comment]
Hi,

That's works perfect. Thanks a lot!

Best,
Jorge
