### ISSUE TITLE
How to generate the input file

### ISSUE THREAD

**Issue by panruiqing** [fastlmm/FaST-LMM#5]
Dear Carl:
 
I want to use FastLMM performing GWAS analysis . However I do not know how to generate the input file ,  just as following:
bed_fn = "../../tests/datasets/synth/all"
pheno_fn = "../../tests/datasets/synth/pheno_10_causals.txt"
cov_fn = "../../tests/datasets/synth/cov.txt"
and what is the  meaning of these file？
Thank you very much.

Ruiqing

**Comment by CarlKCarlK** [comment]
Ruiqing,

Thanks for using FaST-LMM. Here is the API documentation for single_snp with details of the inputs: https://fastlmm.github.io/FaST-LMM/#single-snp
  (Thanks to your note, I just found some bad links in API documentation. The links should be fixed now.)

The main inputs are:

  *   test_snp – the SNP information for a population of individuals for the DNA locations you wish to test
  *   pheno – the trait (for example, the presence/absence of some disease ) for the individuals
  *   covar – (optional) any non-genetic information about the individuals (for example, height, weight) that the single_snp should consider.

You can download the sample files, if you like, from https://github.com/fastlmm/FaST-LMM/.

If you have data in a different format, just let me know what it is and I may be able to offer advice on using it with the program.

Yours,
Carl


Carl Kadie, Ph.D.
FaST-LMM & PySnpTools Team
(Microsoft Research, retired)
Join the FaST-LMM user discussion and announcement list via email<mailto:fastlmm-user-join@python.org?subject=Subscribe> (or use web sign up<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fmail.python.org%2Fmailman3%2Flists%2Ffastlmm-user.python.org&data=02%7C01%7C%7C540f44c603f74286262e08d7bf9aa5bc%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637188543563267798&sdata=yLg%2FFSbov8heBrDG0d4WAYZd%2B%2BkSjoZZMGrkYUZAD3I%3D&reserved=0>)

**Comment by panruiqing** [comment]
Dear Carl:

Thank you very much. The test_snp file I have is in a vcf format which contains the SNP information for a population of individuals for the DNA locations. The pheno file I have is a matrix which contains the phenotype for the individuals. I do not have the covar file. Can I use these two files to performing GWAS analysis. Thank you again.

The  vcf format :
<img width="899" alt="vcf" src="https://user-images.githubusercontent.com/41359724/76391627-da859880-63aa-11ea-8bf7-15cc8977e56e.png">

The phenotype ：
<img width="880" alt="pheno" src="https://user-images.githubusercontent.com/41359724/76391620-d48fb780-63aa-11ea-9ef2-fd3f6ee96764.png">

**Comment by CarlKCarlK** [comment]
Ruiqing,

Great!

First, convert the VCF format to PLINK Bed/Fam/Bim format. (Any method is fine, but here is a thread on biostars on how to do this: https://www.biostars.org/p/313943/).
If you look at the created Fam file (which is just a text file about the individuals), you’ll see that individuals have a two-part ID: a family part and an individual part.

Second, use a text editor (or a little program) to create a *.phe Pheno type file for your phenotype of interest in this form (where the first two columns are the two-part individual id):

[A screenshot of a computer  Description automatically generated]
Then run:

from fastlmm.association import single_snp
single_snp(bedfile, phenofile, output_file_name="output.txt")


Let me know if you have any problems. If you want to run multiple phenotypes, I can show you how, but it would help if you could show me a sample of the *.fam file that you create.

Yours,
Carl

**Comment by panruiqing** [comment]
Dear Carl:
 Thank you for your advice ,I have run fastlmm to perform gwas analysis successfully ( just for one phenotype).  I have another question. if the pheo file has missing value for a individual, which number standas for this missing value, just as the following picture:
![phe](https://user-images.githubusercontent.com/41359724/76508535-87364780-6489-11ea-98a8-88a492c06b9e.png)
and I really need run multiple phenotypes,the following is the *fam file.
![fam](https://user-images.githubusercontent.com/41359724/76508962-307d3d80-648a-11ea-86ec-9f0958edfbf0.png)

what is  your advice ? Thank you very much.

Ruiqing

**Comment by CarlKCarlK** [comment]
Ruiqing,

By default missing values in the Phenotype file should be marked with 'NaN'. For example, here is a little phenofile:

[A screenshot of a cell phone  Description automatically generated]

(There is a way to change that default. Let me know if you need to know.)

  *   I really need run multiple phenotypes,the following is the *fam file.

I'm not sure I understand. According to http://zzz.bwh.harvard.edu/plink/data.shtml, the contents of the fam file is:
     Family ID
     Individual ID
     Paternal ID
     Maternal ID
     Sex (1=male; 2=female; other=unknown)
     Phenotype

Typically, only the first two columns are used. (In your example, file, it doesn't look like any of the other values are meaningful, just 0's and -9's).

A given GWAS run is for one phenotype. If we have multiple phenotypes, we just do multiple runs.

However, sometimes we have additional information, called the covariate, that along with the SNPs is used to predict the phenotype. The covariate is typically demographic information such as sex and age. single_snp has an optional "covar" input. The default file format is the same as for pheno, but multiple columns are fine.

Does this help?

  *   Carl
