### ISSUE TITLE
using only one chromosome

### ISSUE THREAD

**Issue by snowformatics** [fastlmm/FaST-LMM#50]
Hi everyone :)

What would be the easiest way to use only one chromosome for single_snp: 

```
bed = Bed(str(bed_path), count_A1=False, chrom_map=chrom_mapping)
pheno = Pheno(str(pheno_path))
bed, pheno = pstutil.intersect_apply([bed, pheno])
bed_fixed = filter_out_missing(bed)
single_snp(bed_fixed, pheno, output_file_name=gwas_result_name)
```

I found an example in the Bed reader documentation (bed3.read(index=np.s_[:,bed3.chromosome=='5'])) but it return a Numpy array and I need a 'pysnptools.snpreader._subset._SnpSubset format to run single_snp.

Thanks in advance

**Comment by snowformatics** [comment]
Sorry, I found it in the PySnpTools docs:
bed = Bed(str(bed_path), count_A1=False)[:, bed.pos[:, 0] == 3].read().

Closing

**Comment by CarlKCarlK** [comment]
Excellent!
