### ISSUE TITLE
fastlmm.association import fails || 86_64-linux-gnu.so: undefined symbol: mkl_serv_inspector_loaded

### ISSUE THREAD

**Issue by complexgenome** [fastlmm/FaST-LMM#6]
Dear Devels,

I'm using conda (`v 4.8.2`) environment, python (`v3.5.5`).  Unix environment (`SMP Debian 4.9.51-1 (2017-09-28) x86_64 GNU/Linux`).

When I try to load fast-lmm library, it fails. Attached is the error message. I installed using pip as `pip install fastlmm` 

Also when I installed using pip, I received warning. Please see attached warning log.

[import_fails.txt](https://github.com/fastlmm/FaST-LMM/files/4325777/import_fails.txt)
[notes_installation.txt](https://github.com/fastlmm/FaST-LMM/files/4325778/notes_installation.txt)

Let me know if I've missed any details or environment information useful to zoom into this.

Thank you

**Comment by CarlKCarlK** [comment]
Sanjeev,

Thanks for using FaST-LMM!

The current version of FaST-LMM is only supports Python 3.7+ and 2.7+

If you can’t upgrade, you may be able to instead install an older version of FaST-LMM from PyPi, but you’ll have to switch to Python 2.
The FaST-LMM version FaST-LMM is https://pypi.org/project/fastlmm/#history

(in an Python 2 environment), something like:
pip install 'fastlmm==0.2.33'


  *   Carl

**Comment by complexgenome** [comment]
Hi Carl,

Thanks for your attention to this error.
I tried to load fastlmm in new conda environment for Python (`v3.7`). Sadly, it doesn't work with Python `3.7.6`. It fails with same error attached (similar to previous one).

Should I try with python `v3.8`?
[error_3.76python.txt](https://github.com/fastlmm/FaST-LMM/files/4325937/error_3.76python.txt)

**Comment by CarlKCarlK** [comment]
Thanks for upgrading Python.

I’m using:
Ubuntu: Python 3.7.4, conda 4.8.2
Windows 10: Python 3.7.4, conda 4.7.12

I’ll try to set up a Debian environment and see if I can repro the issue, but it will likely be tonight before I can get to it.


  *   Carl

**Comment by CarlKCarlK** [comment]
I just got FaST-LMM to work with Debian 10, Anaconda 2020.02 and Python 3.7.6. Below are my steps (including missteps).

Does this help?


  *   Carl



  *   From Windows store, install Debian
  *   cat /etc/debian_version
     *   10.0
  *   Download https://repo.anaconda.com/archive/Anaconda3-2020.02-Linux-x86_64.sh to /mnt/c/Users/Carl/Downloads
  *   cd /mnt/c/Users/Carl/Downloads
  *   bash Anaconda3-2020.02-Linux-x86_64.sh
     *   installs Python 3.7.6
  *   (answer questions and then restart Debian)
  *   pip install fastlmm
     *   failed
  *   pip install fastlmm
     *   failed again
  *   pip install pysnptools
     *   failed
  *   sudo pip install pysnptools
     *   couldn’t find pip
  *   pip install pysnptools --no-use-pep517
     *   doesn’t know ‘gcc’
  *   sudo apt-get install gcc
     *   can’t find
  *   sudo apt-get update
  *   sudo apt-get install gcc
  *   pip install pysnptools --no-use-pep517
     *   gcc: error trying to exec 'cc1plus': execvp: No such file or directory
  *   pip install pysnptools
     *   same error
  *   sudo apt-get install g++
  *   pip install pysnptools --no-use-pep517
     *   works!
  *   pip install fastlmm
     *   works!
  *   python
     *   starts python
  *   from fastlmm.association import single_snp
     *   returns (so it finds single_snp)
  *   exit()
     *   leaves python



From: Carl KADIE
Sent: Thursday, March 12, 2020 12:01 PM
To: fastlmm/FaST-LMM <reply@reply.github.com>; fastlmm/FaST-LMM <FaST-LMM@noreply.github.com>
Cc: Comment <comment@noreply.github.com>
Subject: RE: [fastlmm/FaST-LMM] fastlmm.association import fails || 86_64-linux-gnu.so: undefined symbol: mkl_serv_inspector_loaded (#6)

Thanks for upgrading Python.

I’m using:
Ubuntu: Python 3.7.4, conda 4.8.2
Windows 10: Python 3.7.4, conda 4.7.12

I’ll try to set up a Debian environment and see if I can repro the issue, but it will likely be tonight before I can get to it.


  *   Carl
