### ISSUE TITLE
SNPs from different replicons should be in one input file or separate?

### ISSUE THREAD

**Issue by limin321** [fastlmm/FaST-LMM#9]
Dear Carl,
Thank you so much for developing this tool. I learned this tool from a paper, and really want to try it with my own data. I want to run association analysis of bacterial SNPs and pheno data.
Now I am in the stage of preparing data, and have some questions on how to prepare my input data specifically.

My bacteria have one circular chromosome, one linear chromosome, and uneven number of plasmids. When I did SNPs calling, they were all in one file. For association analysis, feels like when I convert from VCF to PLINK format, I could either convert in one file, or convert each replicon individually. For association analysis, should SNPs from different replicons be in one file or separately?
Also, because the uneven number of plasmids, the end of the SNPs file looks like this:

<img width="948" alt="Screen Shot 2020-11-10 at 11 23 38 PM" src="https://user-images.githubusercontent.com/42760669/98781775-c667c000-23ab-11eb-88ca-d29c42a4f530.png">
I don't know why there are so many 0, and they don't align because different numbers of SNP in each bacterium. Will that be a problem for association anaylsis?

For phenotypic data, I have 11 different traits, should I run each trait one by one, or I can merge SNPs data with all 11 traits to one file, and have FaSTlmm to run all at once?

Thank you so much,
Best,
Limin

**Comment by CarlKCarlK** [comment]
Limin,

Thanks for considering FaST-LMM!

I passed your question on to a FaST-LMM co-author and he recommends this article:
https://journals.plos.org/plosgenetics/article?id=10.1371/journal.pgen.1007758#:~:text=The%20aim%20of%20Genome-Wide,data%20%5B1%E2%80%937%5D


  *   Carl


p.s. Follow up with us with any questions on data formats, working with multiple phenotypes, etc. If you can, include the approximate size of the datasets.


Carl Kadie, Ph.D.
FaST-LMM & PySnpTools Team<https://fastlmm.github.io/>
(Microsoft Research, retired)
https://www.linkedin.com/in/carlk/

Join the FaST-LMM user discussion and announcement list via email<mailto:fastlmm-user-join@python.org?subject=Subscribe> (or use web sign up<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fmail.python.org%2Fmailman3%2Flists%2Ffastlmm-user.python.org&data=02%7C01%7C%7C13a5c33d7cd84cad5cdf08d7bba56e20%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637184191498409587&sdata=2CQWjQEwOpQol2rQ1eoyVTgY8WvInV8UH31Wtl68FzY%3D&reserved=0>)

**Comment by limin321** [comment]
> Limin, Thanks for considering FaST-LMM! I passed your question on to a FaST-LMM co-author and he recommends this article: https://journals.plos.org/plosgenetics/article?id=10.1371/journal.pgen.1007758#:~:text=The%20aim%20of%20Genome-Wide,data%20%5B1%E2%80%937%5D * Carl p.s. Follow up with us with any questions on data formats, working with multiple phenotypes, etc. If you can, include the approximate size of the datasets. Carl Kadie, Ph.D. FaST-LMM & PySnpTools Team<https://fastlmm.github.io/> (Microsoft Research, retired) https://www.linkedin.com/in/carlk/ Join the FaST-LMM user discussion and announcement list via email<mailto:fastlmm-user-join@python.org?subject=Subscribe> (or use web sign up<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fmail.python.org%2Fmailman3%2Flists%2Ffastlmm-user.python.org&data=02%7C01%7C%7C13a5c33d7cd84cad5cdf08d7bba56e20%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637184191498409587&sdata=2CQWjQEwOpQol2rQ1eoyVTgY8WvInV8UH31Wtl68FzY%3D&reserved=0>) From: limin <notifications@github.com> Sent: Tuesday, November 10, 2020 11:30 PM To: fastlmm/FaST-LMM <FaST-LMM@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: [fastlmm/FaST-LMM] SNPs from different replicons should be in one input file or separate? (#9) Dear Carl, Thank you so much for developing this tool. I learned this tool from a paper, and really want to try it with my own data. I want to run association analysis of bacterial SNPs and pheno data. Now I am in the stage of preparing data, and have some questions on how to prepare my input data specifically. My bacteria have one circular chromosome, one linear chromosome, and uneven number of plasmids. When I did SNPs calling, they were all in one file. For association analysis, feels like when I convert from VCF to PLINK format, I could either convert in one file, or convert each replicon individually. For association analysis, should SNPs from different replicons be in one file or separately? Also, because the uneven number of plasmids, the end of the SNPs file looks like this: [Screen Shot 2020-11-10 at 11 23 38 PM]<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F42760669%2F98781775-c667c000-23ab-11eb-88ca-d29c42a4f530.png&data=04%7C01%7C%7C2c8d80cfe208437263b308d886138cdb%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637406765802359009%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=OIgZOpKVxa1uFYPMIGH%2FtppK4YOTPbxjdc7fXYXm3%2BQ%3D&reserved=0> I don't know why there are so many 0, and they don't align because different numbers of SNP in each bacterium. Will that be a problem for association anaylsis? For phenotypic data, I have 11 different traits, should I run each trait one by one, or I can merge SNPs data with all 11 traits to one file, and have FaSTlmm to run all at once? Thank you so much, Best, Limin — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Ffastlmm%2FFaST-LMM%2Fissues%2F9&data=04%7C01%7C%7C2c8d80cfe208437263b308d886138cdb%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637406765802359009%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=ONccSECeTe6ajvGNdFW01yqwCpzMTBIUYMUzxjaPzGI%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FABR65P6YIHEFQ5H6DPVZOPLSPI4OHANCNFSM4TRUWQOQ&data=04%7C01%7C%7C2c8d80cfe208437263b308d886138cdb%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637406765802369006%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=IvgralbVHYlaMzMz%2Fai%2Bf5H0nre5TG4uGQGstf4DsQc%3D&reserved=0>.

Hi Carl

Thank you and your friend who suggest the paper. I finally made it run. I am learning how to interpret the data.
Actually I still want to try out your model, which I learned from this paper.
https://github.com/fastlmm/FaST-LMM/issues/9#issuecomment-725735080
they applied your model and got really nice results. I am considering try different method to confirm my results.

Do you have any recommendation on my previous question if try to use your model?

Thank you so much.
Best,
Limin

**Comment by CarlKCarlK** [comment]
Limin,

  *   Do you have any recommendation on my previous question if try to use your model?
  *   For association analysis, should SNPs from different replicons be in one file or separately?
I’m sorry, I don’t know. (I’ve worked almost exclusively with human DNA.)

  *   I don't know why there are so many 0, and they don't align because different numbers of SNP in each bacterium. Will that be a problem for association analysis?

I’m not sure, but I think good alignment is important. For human DNA, I believe every SNP location has a name (for example, “rs6311<https://en.wikipedia.org/wiki/Rs6311>”) and I known location in the data. If the GWAS says that SNP is significant, we know that means.


  *   For phenotypic data, I have 11 different traits, should I run each trait one by one, or I can merge SNPs data with all 11 traits to one file, and have FaSTlmm to run all at once?

This question I can answer! The main GWAS function in FaST-LMM is single_snp<https://fastlmm.github.io/FaST-LMM/#single-snp>. It only knows how to process one phenotype at a time so the simplest thing is to put each phenotype in its own file and do 11 runs. (One phenotype text format is described here<https://fastlmm.github.io/PySnpTools/#snpreader-pheno>.). This approach also better handles the case in which different phenotypes have different missing data.

(Details: A different GWAS function called single_snp_scale can run multiple phenotypes at once, but it is generally slower until the size of the problem gets larger than 50,000+. Also, it is possible for the single_snp function to read just one phenotype at a time from a phenotype file that contains multiple phenotypes, but I suggest getting it working one phenotype first.)


  *   Carl
